// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5twUBBYAWAU7LrA9gHFKC1AjoMoZ5WQs',
    appId: '1:252684291454:android:2047f678f6c6d93bb8b72f',
    messagingSenderId: '252684291454',
    projectId: 'ecom-mart-8d90b',
    databaseURL: 'https://ecom-mart-8d90b-default-rtdb.firebaseio.com',
    storageBucket: 'ecom-mart-8d90b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC34TQ_6RjyC3EzUWq-ZiCQdghxae0_zwg',
    appId: '1:252684291454:ios:654d977cbda48016b8b72f',
    messagingSenderId: '252684291454',
    projectId: 'ecom-mart-8d90b',
    databaseURL: 'https://ecom-mart-8d90b-default-rtdb.firebaseio.com',
    storageBucket: 'ecom-mart-8d90b.appspot.com',
    iosBundleId: 'com.example.sih',
  );
}
